import SellIcon from "@mui/icons-material/Sell";
export const MovieCatData = [
  {
    id: 1,
    title: "افلام",
    log: <SellIcon />,
  },
  {
    id: 2,
    title: "احدث الاضافات",
    log: <SellIcon />,
  },
  {
    id: 3,
    title: "افضل الافلام",
    log: <SellIcon />,
  },
  {
    id: 4,
    title: "الاكثر شهره",
    log: <SellIcon />,
  },
];

export const movieTypeData = [
  {
    id: 1,
    type1: "السنه",
    type2: "2022",
    type3: "2021",
    type4: "2020",
    type5: "2019",
  },
  {
    id: 2,
    main: "اللغه",
    type1: "اللغه",
    type2: "الانجليزيه",
    type3: "الفرنسيه",
    type4: "البرتغاليه",
    type5: "الارجنتينيه",
  },
  {
    id: 3,
    main: "البلد",
    type1: "السودان",
    type2: "مصر",
    type3: "الولايات المتحده",
    type4: "المملكه المتحده",
    type5: "البرازيل",
  },
  {
    id: 4,
    main: "النوع",
    type1: "التصنيف",
    type2: "اكشن",
    type3: "مغامره",
    type4: "خيال",
    type5: "فانتازيا",
  },
  {
    id: 5,
    main: "التصنيف",
    type1: "سفاري",
    type2: "اكشن",
    type3: "مغامره",
    type4: "خيال",
    type5: "فانتازيا",
    type6: "مانغا",
  },
  {
    id: 6,
    main: "الجوده",
    type1: "1080",
    type2: "720",
    type3: "480",
    type4: "320",
    type5: "220",
  },
  {
    id: 7,
    main: "الدقه",
    type1: "2022",
    type2: "2021",
    type3: "2020",
    type4: "2019",
    type5: "2018",
  },
  {
    id: 8,
    main: "الترجمه",
    type1: "العربيه",
    type2: "الانجليزيه",
    type3: "الفرنيسه",
    type4: "البرتقاليه",
    type5: "الارجنتينيه",
    type6: "السوريه",
    type7: "السودانيه",
    type8: "المصريه",
  },
];
